version: "3.9"
services:
  worker:
    build:
      context: ../..
      dockerfile: ../../Dockerfile
    image: ${REPOSITORY_NAME:-heroku-aws-connector}:${VERSION:-0.1}
    environment:
      - HEROKU_API_KEY=${HEROKU_API_KEY}
      - HEROKU_APP_NAME=${HEROKU_APP_NAME}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    entrypoint: /run/script.sh
    logging:
      driver: json-file
      options:
        max-size: 100m
volumes:
  logvolume01: {}